# Default initial positions for ur10_double's ros2_control fake system

initial_positions:
  ur10_1_elbow_joint: 0
  ur10_1_shoulder_lift_joint: 0
  ur10_1_shoulder_pan_joint: 0
  ur10_1_wrist_1_joint: 0
  ur10_1_wrist_2_joint: 0
  ur10_1_wrist_3_joint: 0
  ur10_2_elbow_joint: 0
  ur10_2_shoulder_lift_joint: 0
  ur10_2_shoulder_pan_joint: 0
  ur10_2_wrist_1_joint: 0
  ur10_2_wrist_2_joint: 0
  ur10_2_wrist_3_joint: 0