# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    robot2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot1_controller:
  ros__parameters:
    joints:
      - ur10_1_shoulder_pan_joint
      - ur10_1_shoulder_lift_joint
      - ur10_1_elbow_joint
      - ur10_1_wrist_1_joint
      - ur10_1_wrist_2_joint
      - ur10_1_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
robot2_controller:
  ros__parameters:
    joints:
      - ur10_2_shoulder_pan_joint
      - ur10_2_shoulder_lift_joint
      - ur10_2_elbow_joint
      - ur10_2_wrist_1_joint
      - ur10_2_wrist_2_joint
      - ur10_2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity